"""Best-effort outgoing webhooks on Mirror-Leech task completion.

A user can register a single webhook URL + shared secret in their
personal settings. When a task finishes (success or permanent failure),
`fire(user_id, event, payload)` builds a JSON body, HMAC-signs it, and
POSTs to the URL. Failure is silent — webhook delivery is a
"best-effort" side channel and must never block the bot.

Retry policy: one retry, 60s later, when the initial request returns
a non-2xx status. That's enough to soak up brief downstream hiccups
without building a full durable-outbox with state persistence.

Payload shape is documented in the plan (Phase D.3.b); the flat dict
we build here mirrors it exactly.

Stored under `personal_settings.mirror_leech_webhook`::

    {
      "url":      "https://example.com/hook",
      "secret":   "<32-char>",
      "events":   ["upload_done", "upload_failed"],  # subset
      "enabled":  true,
    }

The secret is plaintext — it's a pre-shared HMAC key, not a
credential. Auto-generated by the config UI.
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import json
import secrets as _secrets
import time
from typing import Any, Optional

from db import db
from utils.telegram.log import get_logger

logger = get_logger("mirror_leech.webhooks")

EVENT_UPLOAD_DONE = "upload_done"
EVENT_UPLOAD_FAILED = "upload_failed"
DEFAULT_EVENTS: tuple[str, ...] = (EVENT_UPLOAD_DONE, EVENT_UPLOAD_FAILED)
_ALL_EVENTS = frozenset({EVENT_UPLOAD_DONE, EVENT_UPLOAD_FAILED})

_REQUEST_TIMEOUT_SEC = 5
_RETRY_DELAY_SEC = 60
_SIGNATURE_HEADER = "X-MediaStudio-Signature"


def generate_secret() -> str:
    """Return a fresh 32-char hex secret."""
    return _secrets.token_hex(16)


async def get_config(user_id: int) -> Optional[dict]:
    """Return the user's webhook config or None if unset."""
    if db.users is None:
        return None
    doc = await db.users.find_one({"user_id": user_id})
    if not doc:
        return None
    personal = doc.get("personal_settings") or {}
    raw = personal.get("mirror_leech_webhook") or None
    if not isinstance(raw, dict):
        return None
    return dict(raw)


async def save_config(user_id: int, cfg: dict) -> None:
    """Upsert the webhook config. Fields are validated lightly — the
    UI does the real prompting, we just sanitise."""
    if db.users is None:
        return
    clean = {
        "url": str(cfg.get("url") or "").strip(),
        "secret": str(cfg.get("secret") or "").strip(),
        "events": sorted(
            {
                str(e)
                for e in (cfg.get("events") or DEFAULT_EVENTS)
                if e in _ALL_EVENTS
            }
        ) or list(DEFAULT_EVENTS),
        "enabled": bool(cfg.get("enabled", True)),
    }
    await db.users.update_one(
        {"user_id": int(user_id)},
        {"$set": {"personal_settings.mirror_leech_webhook": clean}},
        upsert=True,
    )


async def clear_config(user_id: int) -> None:
    if db.users is None:
        return
    await db.users.update_one(
        {"user_id": int(user_id)},
        {"$unset": {"personal_settings.mirror_leech_webhook": ""}},
    )


def _sign(secret: str, body: bytes) -> str:
    mac = hmac.new(secret.encode("utf-8"), body, hashlib.sha256).hexdigest()
    return f"sha256={mac}"


async def _post(url: str, body: bytes, signature: str) -> tuple[bool, int, str]:
    """POST once; return (ok, status, short_body). `ok` is True iff
    status in 200-299. Swallows exceptions as (False, 0, exc)."""
    import aiohttp

    try:
        timeout = aiohttp.ClientTimeout(total=_REQUEST_TIMEOUT_SEC)
        async with aiohttp.ClientSession(timeout=timeout) as http, http.post(
            url,
            data=body,
            headers={
                "Content-Type": "application/json",
                _SIGNATURE_HEADER: signature,
                "User-Agent": "XTV-MediaStudio-Webhook/1.0",
            },
        ) as resp:
            text = (await resp.text())[:200]
            return 200 <= resp.status < 300, resp.status, text
    except Exception as exc:
        return False, 0, str(exc)[:200]


async def test_send(user_id: int) -> tuple[bool, str]:
    """Ping the configured webhook with a synthetic payload. Used by
    the config UI's "Test send" button."""
    cfg = await get_config(user_id)
    if not cfg or not cfg.get("url") or not cfg.get("secret"):
        return False, "Webhook not configured"
    payload = {
        "event": "test",
        "user_id": int(user_id),
        "timestamp": _iso_now(),
        "message": "MediaStudio test payload — nothing happened on your account.",
    }
    body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    signature = _sign(cfg["secret"], body)
    ok, status, text = await _post(cfg["url"], body, signature)
    if ok:
        return True, f"delivered ({status})"
    return False, f"status={status} body={text}"


def _iso_now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


async def fire(
    user_id: int,
    event: str,
    payload: dict[str, Any],
) -> None:
    """Dispatch `event` to the user's webhook if configured, enabled,
    and subscribed to the event. Errors are logged at debug level."""
    cfg = await get_config(user_id)
    if not cfg:
        return
    if not cfg.get("enabled", True):
        return
    if event not in set(cfg.get("events") or []):
        return
    url = cfg.get("url") or ""
    secret = cfg.get("secret") or ""
    if not url or not secret:
        return

    body_dict = {
        "event": event,
        "user_id": int(user_id),
        "timestamp": _iso_now(),
        **payload,
    }
    body = json.dumps(body_dict, separators=(",", ":")).encode("utf-8")
    signature = _sign(secret, body)

    ok, status, text = await _post(url, body, signature)
    if ok:
        logger.info(
            "webhook %s → %s delivered (status=%d)", event, url, status
        )
        return

    # Single retry after 60s. Fire-and-forget: the caller has already
    # moved on by the time this runs.
    async def _retry() -> None:
        await asyncio.sleep(_RETRY_DELAY_SEC)
        rok, rstatus, rtext = await _post(url, body, signature)
        if rok:
            logger.info(
                "webhook %s → %s delivered on retry (status=%d)",
                event, url, rstatus,
            )
        else:
            logger.debug(
                "webhook %s → %s retry failed (status=%d body=%s)",
                event, url, rstatus, rtext,
            )

    logger.debug(
        "webhook %s → %s first attempt failed (status=%d body=%s), scheduling retry",
        event, url, status, text,
    )
    asyncio.create_task(_retry())


def build_task_payload(task_id: str, source: str, results: list) -> dict:
    """Lift an MLTask's UploadResult list into the JSON-serialisable
    dict the webhook payload expects."""
    providers: dict[str, dict] = {}
    for r in results:
        providers[r.uploader_id] = {
            "ok": bool(r.ok),
            "url": r.url,
            "message": r.message,
        }
    return {
        "task_id": str(task_id),
        "source_url": source,
        "providers": providers,
    }


def build_failure_payload(
    task_id: str,
    source: str,
    error: str,
    attempt: int,
    max_attempts: int,
) -> dict:
    return {
        "task_id": str(task_id),
        "source_url": source,
        "error": error,
        "attempt": int(attempt),
        "max_attempts": int(max_attempts),
    }


# --- paste-time helpers -------------------------------------------------


def valid_http_url(url: str) -> bool:
    """Loose URL validator — anything with http/https and a host."""
    u = (url or "").strip().lower()
    return u.startswith(("http://", "https://")) and len(u) > 10


# --------------------------------------------------------------------------
# Developed by 𝕏0L0™ (@davdxpx) | © 2026 XTV Network Global
# Don't Remove Credit
# Telegram Channel @XTVbots
# Developed for the 𝕏TV Network @XTVglobal
# Backup Channel @XTVhome
# Contact on Telegram @davdxpx
# --------------------------------------------------------------------------
